name: SimpleHelpTickets
main: me.odium.simplehelptickets.SimpleHelpTickets
version: 1.4.2
authors: [Odium, dmulloy2]
description: >
             Comprehensive "ticket" plugin allowing members to receive help, even when staff isn't online.
             Version 1.4.2: Removes a listener that was causing unnecessary lag.
commands:
   sht:
      aliases: [helptickets, simplehelptickets]
      description: Help Menu
      permission: sht.help
      usage: /sht
   ticket:
      aliases: [helpme, grief]
      description: Open a help ticket
      permission:
      usage: /ticket <Description>
   tickets:
      description: Review your/all help tickets
      permission:
      usage: /tickets [ac]  
   closeticket:
      description: close or reopen a help ticket
      permission: 
      usage: /closeticket [r] <#>
   replyticket:
      aliases: [rticket]
      description: 
      permission:
      usage: /replyticket <#> <reply>
   taketicket:
      description: Assign self to a help ticket
      permission: sht.moderator
      usage: /taketicket <#>
   checkticket:
      aliases: [chticket]
      description: check your/a help ticket
      permission: 
      usage: /checkticket <#>
   delticket:
      aliases: [dticket]
      description: Delete a ticket
      permission: 
      usage: /delticket <#>
   purgetickets:
      aliases: [ptickets]
      description: Purge all expired tickets
      permission: 
      usage: /purgetickets
permissions:
    sht.admin:
        description: Gives access to all SHT features.
        children:
            sht.moderator: true
            sht.default: true
            sht.help: true
    sht.moderator:
        description: Gives access to features intended for moderators.
        children:
            sht.default: true
            sht.help: true
    sht.default:
        description: Gives access to features intended for simpletons.
        children:
            sht.help: true